# Generated by Django 3.2.25 on 2026-03-18 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import writing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text_input', models.TextField(help_text='Original text used for generation')),
                ('parameters', models.JSONField(default=dict, help_text='Generation parameters: style, bias, stroke_width, use_margins')),
                ('pages_generated', models.PositiveIntegerField(default=0)),
                ('generation_time', models.FloatField(default=0.0, help_text='Generation time in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_generators', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=writing.models.generation_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='writing.generation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['generation'], name='writing_use_generat_21ad7c_idx'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['user', '-created_at'], name='writing_use_user_id_606202_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', '-created_at'], name='writing_gen_user_id_f6b91f_idx'),
        ),
    ]
