# Generated by Django 3.2.25 on 2025-07-22 14:18

from django.db import migrations, models
import writing.models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=writing.models.user_directory_path),
        ),
    ]
