# Generated by Django 3.2.25 on 2025-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_userimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_generators', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
